config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path => '/profile', controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#main_page'
  # get '/test_path', to: 'pages#test_path'
  get '/video'    , to: 'pages#video'
  get '/about'    , to: 'pages#about'
  get '/gifs_some1'    , to: 'pages#gifs_some1'
  get '/gg5_v1'    , to: 'pages#gg5_v1'
  get '/gg5_v2'    , to: 'pages#gg5_v2'
  get '/games', to: 'pages#games'
  get '/new_animes', to: 'pages#new_animes'
  get '/create_animes_snapshot', to: 'pages#create_animes_snapshot'



  # get '/parties'                                , to: 'pages#front_parties_list'
  # get '/parties/:party_id'                      , to: 'pages#front_parties_edit'
  # get '/parties/:party_id/buy_ticket/:tpack_id' , to: 'pages#front_parties_buy_ticket'

  resources :queues, module: :pub_task_queues, param: :tq_id, only: [:index, :show, :update] do

  end
  # resources :tasks, module: :front_users_module, param: :front_user_id, only: [:index, :show] do

  #   end

  resources :users, module: :front_users_module, param: :front_user_id, only: [:index, :show] do

  end

  resources :parties, module: :parties_module, param: :party_id, only: [:index, :show] do
    resources :tickets, module: :buy_ticket_module, param: :tpack_id, only: [:index] do

    end
    member do
      get :chat
      post :chat, to: 'parties#chat_add_msg'
    end
  end

  resources :trips, module: :pub_trips, param: :tr_id, only: [:index, :show] do
    resources :points, param: :trp_id, only: [:index, :show] do

    end
    member do
      get :chat
      post :chat, to: 'trips#chat_add_msg'
    end
  end

  resources :stations, module: :pub_stations, param: :st_id, only: [:index, :show] do

  end


  get  '/profile'                             , to: 'front_profile#user_profile_show', as: :user_root
  get  '/profile/public_info'                 , to: 'front_profile#user_profile_public_info_edit'
  post '/profile/public_info'                 , to: 'front_profile#user_profile_public_info_save'
  get  '/profile/password_change'             , to: 'front_profile#user_profile_password_change_edit'
  post '/profile/password_change'             , to: 'front_profile#user_profile_password_change_save'
  get  '/profile/change_email'                , to: 'front_profile#user_profile_change_email_edit'
  post '/profile/change_email'                , to: 'front_profile#user_profile_change_email_save'
  post '/profile/subscribe_notifications'     , to: 'front_profile#subscribe_notifications'
  post '/demo_push'                           , to: 'pages#demo_push'
  # get  '/profile/my_events'                   , to: 'front_profile#user_profile_my_events_list'
  # get  '/profile/my_events/:my_event_id'      , to: 'front_profile#user_profile_my_events_show'
  # post '/profile/my_events/:my_event_id'      , to: 'front_profile#user_profile_my_events_save'
  # get  '/profile/my_events/:my_event_id/edit' , to: 'front_profile#user_profile_my_events_show'
  # PAYMENT CALLBACKS STARTED
  # post "/webhooks/stripe", to: "pay/webhooks/stripe#create"

  get  "/payment_success/:ticket_payment_id", to: 'pages#ticket_transaction_payment_success'
  get  "/payment_cancel/:ticket_payment_id" , to: 'pages#ticket_transaction_payment_cancel'


  get '/vehicle_img_sm/:vimg_id', :controller => :pages, action: :pub_vehicle_sm_img
  get '/user_station_img_sm/:simg_id', :controller => :pages, action: :pub_user_station_sm_img

  namespace :profile, format: false do
    resources :my_payout_options, module: :my_payout_options, param: :poption_id
    resources :my_notifications, module: :my_notifications, param: :my_notification_id, only: [:index, :show]
    resources :my_tickets, module: :my_tickets, param: :ticket_id, only: [:index, :new, :show, :create, :update] do
      get :pay
    end
    resources :my_vehicles, module: :my_vehicles, param: :my_vehicle_id do
      resources :vehicle_imgs, param: :eimg_id, only: %w{index create destroy} do

      end
      member do
        post :choose_vimage_as_logo
      end
    end

    resources :my_stations, module: :my_stations, param: :my_station_id do
      resources :station_imgs, param: :simg_id, only: %w{index create destroy} do

      end
      member do
        post :choose_simage_as_logo
      end
    end

    resources :my_routes, module: :my_routes, param: :my_route_id do
      resources :route_points, param: :rp_id do

      end
      # member do
      #   post :choose_simage_as_logo
      # end
    end

    resources :my_trips, module: :my_trips, param: :my_trip_id do
      resources :trip_points, param: :trp_id do

      end
      member do
        get  :publish_flag
        post :publish_flag, to: 'my_trips#publish_flag_update'
      end
      # resources :route_points, param: :rp_id do

      # end
    end

    resources :my_events, module: :my_events, param: :my_event_id do
      resources :tickets_packs, param: :tpack_id do

      end
      member do
        get :images
        get  :my_chat
        post :my_chat, to: 'my_events#my_chat_add_msg'
        get  :payout
        post :payout , to: 'my_events#payout_run'
        post   :choose_image_as_logo
        post   :create_image_attachment
        post   :change_event_status
      end
    end

    resources :sold_tickets, module: :sold_tickets, param: :sold_ticket_id
  end

end

app/controllers/pub_trips/points_controller.rb
class ::PubTrips::PointsController < ::PubTrips::PubTripsBaseController
  before_action :set_current_trip_point
  skip_before_action :set_current_trip_point, only: %w{index new create}


  def set_current_trip_point
    return @current_trip_point if @current_trip_point
    add_breadcrumb "TripPoints", trip_points_path(@front_side_current_trip.id)
    id = params[:trp_id] || params[:trip_trp_id] || 0
    result = @front_side_current_trip.user_route.user_route_points.detect { |x| x.id.eql?(id.to_i) }
    unless result
      raise ActionController::RoutingError.new("TripPoint[#{ id }] not found in trip[#{ @front_side_current_trip.id }]")
    end
    add_breadcrumb "TripPoint \##{ result.id }", trip_point_path(@front_side_current_trip.id, result.id)
    main_data[:title] = "TripPoint \##{ result.id }"
    @current_trip_point = result
    result
  end

  def index
    add_breadcrumb "TripPoints", profile_my_trip_trip_points_path(@front_side_current_trip.id)
    # @item = @front_side_current_trip.trip_points.new()
    main_data[:title] = "TripPoints"
    @items = @front_side_current_trip.user_route.valid_route_points
  end

  def show
    @item = @current_trip_point
  end


end

app/controllers/pub_trips/pub_trips_base_controller.rb
# frozen_string_literal: true

class ::PubTrips::PubTripsBaseController < ::PagesController
  add_breadcrumb "Trips", :trips_path
  before_action :set_front_side_current_trip

  def set_front_side_current_trip
    return @front_side_current_trip if @front_side_current_trip
    id = params[:tr_id] || params[:trip_tr_id]
    result = Trip.find(Integer(id))
    unless result
      raise ActionController::RoutingError.new("Trip #{ id } not found")
    end
    main_data[:title] = "Trip \##{ result.id }"
    add_breadcrumb main_data[:title], trip_path(result.id)
    @front_side_current_trip = result
    result
  end

  helper_method :can_current_user_read_trip_chat?
  def can_current_user_read_trip_chat?
    return false unless current_user && @front_side_current_trip
    # result = false
    # current_user.tickets.where(event_ticket_pack: @front_side_current_trip.trip_ticket_packs).each do |ticket|
    #   result = true if ticket.ticket_allow_user_to_see_chat?
    # end
    # result
    true
  end
end

app/controllers/pub_trips/trips_controller.rb
# frozen_string_literal: true

class ::PubTrips::TripsController < ::PubTrips::PubTripsBaseController
  skip_before_action :set_front_side_current_trip, only: %w{index new create}


  def index
    per_page = 24
    # data = ::PubTripsSearchHelper.get_trips_collection(params)
    # events = data[:items]
    search_item = { name: 'Search', prop_name: :search }
    # @filter_items = [search_item] + data[:filter_items]
    ids_sql = ::PubTripsSearchHelper.get_search_where_sql(params[:search].to_s, true)
    @filter_items = [search_item]
    # @items = events.page(params_page).per(per_page)
    @items = Trip.active.published_only.where(ids_sql).page(params_page).per(per_page)
  end

  def show
    @item = @front_side_current_trip
  end

  def chat
    @new_msg = TripChatMsg.new
    @items = load_chat_msgs_list
    @unread_ids = load_unreaded_msgs_ids_and_mark_them_readed(@items)
  end

  def load_chat_msgs_list
    per_page = 30
    main_data[:title] = "Trip \##{ @front_side_current_trip.id } Chat"
    add_breadcrumb 'Chat', chat_trip_path(@front_side_current_trip.id)
    search_attrs = can_current_user_read_trip_chat? ? { trip: @front_side_current_trip } : { id: 0 }
    TripChatMsg.where(search_attrs).order(id: :DESC).page(params_page).per(per_page)
  end

  def load_unreaded_msgs_ids_and_mark_them_readed(msgs)
    result = []
    TripChatMsgUnread.where(user: current_user).where(trip_chat_msg_id: msgs.map(&:id)).includes(:trip_chat_msg).each do |umsg|
      result.push(umsg.trip_chat_msg_id)
      if (umsg.trip_chat_msg.created_at + 5.seconds) < Time.now()
        umsg.destroy!
      end
    end
    result
  end

  def chat_add_msg
    @new_msg = TripChatMsg.new
    new_html = params[:msg_text].strip.gsub(/[\r]+/, "").text_to_html
    if can_current_user_read_trip_chat? && new_html.size_positive?
      new_attrs = { user: current_user, msg_html: new_html }
      @new_msg = @front_side_current_trip.trip_chat_msgs.create!(new_attrs)
      if @new_msg.id && @new_msg.id.positive?
        return redirect_to chat_trip_path(@front_side_current_trip.id)
      end
    end
    @items = load_chat_msgs_list
    @unread_ids = load_unreaded_msgs_ids_and_mark_them_readed(@items)
    flash2 :alert, "Errors found"
    render action: :chat
  end
end

app/views/pub_trips/points/index.erb
<div class='row front_content_main_row front_parties_edit_main_row'>
  <div class="w500_centerd" id="content">
    <div class="row front_page_content_row">
      <div class="col-12">
        <div class="row">
          <div class="col-12">
            <h3>TripPoints list</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <table class="table table-sm">
              <thead>
                <tr>
                  <th></th>
                  <th>Logo</th>
                  <th>Point info</th>
                  <th>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @items.each_with_index do |rpoint, indx| %>
                  <tr>
                    <td><%= indx + 1 %></td>
                    <td>
                      <img src="<%= rpoint.route_logo_sm_url %>" />
                    </td>
                    <td>
                      <%= rpoint.user_station.name.ehtml %>
                    </td>
                    <td>
                      <a href="<%= trip_point_path(@front_side_current_trip.id, rpoint.id) %>" class="fa fa-edit" aria-hidden="true" title='View trip point info'></a>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br /><br /><br /><br />
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            <br /><br /><br /><br /><br /><br />
            <%= link_to "Back to trip page", trip_path(@front_side_current_trip.id) %>
            <br/><br/><br/><br/><br/>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pub_trips/points/show.erb
<div class='row front_content_main_row front_parties_edit_main_row'>
  <div class="w500_centerd" id="content">
    <div class="row front_page_content_row">
      <div class="col-12">
        <div class="row profile_station_images_block">
          <div class="col-12 catalog_item_img_block2">
            <% if @item.user_station.valid_station_imgs.any? %>
              <div class="owl-carousel owl-theme owl_prod_list_slider">
                <% @item.user_station.valid_station_imgs.each do |sm_img| %>
                  <div class='item'>
                     <table>
                        <tbody>
                           <tr>
                              <td>
                                <img class='slider_sm_img' src='<%= sm_img.image_sm_url %>' />
                              </td>
                           </tr>
                        </tbody>
                     </table>
                  </div>
                <% end %>
             </div>
            <% else %>
              <div class="catalog_item_subimg_block">
                <div class="catalog_item_img_cell">
                  <img src="/pics/no_image.png" alt="" title="" />
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="col-12">
          <div class="row">
            <div class="col-12">
              <div class="form-group">
                <label>Station:</label>
                <a href="<%= station_path(@item.user_station.id) %>" title='View more info about this station' onclick="return show_in_modal_link(this, 'proj_modal_main station_modal');">
                  <%= @item.user_station.name.ehtml %>
                </a><br />
                Coords: <%= @item.user_station.station_coords_html %><br/>
                <a target="_blank" href="http://maps.google.com/?q=<%= ERB::Util.url_encode(@item.user_station.name) %>@<%= @item.user_station.station_lat_f64 %>,<%= @item.user_station.station_lng_f64 %>">
                  Show at google_maps v3
                </a><br/>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-5">
            <label>Come at (<span title='after_start_planned_seconds'><%= @item.after_start_planned_seconds %>s</span>):</label>
          </div>
          <div class="col-7">
            <%= @item.rpoint_come_time(@front_side_current_trip.trip_start_time_unix_with_default).client_stamp_html %><br/>
          </div>
        </div>
        <div class="row">
          <div class="col-5">
            <label>Away at (<span title='station_stay_seconds'><%= @item.station_stay_seconds %>s</span>):</label>
          </div>
          <div class="col-7">
            <%= @item.rpoint_away_time(@front_side_current_trip.trip_start_time_unix_with_default).client_stamp_html %><br/>
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            &nbsp;<br /><br />
          </div>
        </div>
        <div class="row hidden_in_modal">
          <div class="col-12">
            <br /><br /><br /><br /><br /><br />
            <%= link_to "Back to TripPoints list", trip_points_path(@front_side_current_trip.id) %>
            <br/><br/><br/><br/><br/>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>