config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path => '/profile', controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#main_page'
  # get '/test_path', to: 'pages#test_path'
  get '/video'    , to: 'pages#video'
  get '/about'    , to: 'pages#about'
  get '/gifs_some1'    , to: 'pages#gifs_some1'
  get '/gg5_v1'    , to: 'pages#gg5_v1'
  get '/gg5_v2'    , to: 'pages#gg5_v2'
  get '/games', to: 'pages#games'
  get '/new_animes', to: 'pages#new_animes'
  get '/create_animes_snapshot', to: 'pages#create_animes_snapshot'



  # get '/parties'                                , to: 'pages#front_parties_list'
  # get '/parties/:party_id'                      , to: 'pages#front_parties_edit'
  # get '/parties/:party_id/buy_ticket/:tpack_id' , to: 'pages#front_parties_buy_ticket'

  resources :queues, module: :pub_task_queues, param: :tq_id, only: [:index, :show, :update] do

  end
  # resources :tasks, module: :front_users_module, param: :front_user_id, only: [:index, :show] do

  #   end

  resources :users, module: :front_users_module, param: :front_user_id, only: [:index, :show] do

  end

  resources :parties, module: :parties_module, param: :party_id, only: [:index, :show] do
    resources :tickets, module: :buy_ticket_module, param: :tpack_id, only: [:index] do

    end
    member do
      get :chat
      post :chat, to: 'parties#chat_add_msg'
    end
  end

  resources :trips, module: :pub_trips, param: :tr_id, only: [:index, :show] do
    resources :points, param: :trp_id, only: [:index, :show] do

    end
    member do
      get :chat
      post :chat, to: 'trips#chat_add_msg'
    end
  end

  resources :stations, module: :pub_stations, param: :st_id, only: [:index, :show] do

  end


  get  '/profile'                             , to: 'front_profile#user_profile_show', as: :user_root
  get  '/profile/public_info'                 , to: 'front_profile#user_profile_public_info_edit'
  post '/profile/public_info'                 , to: 'front_profile#user_profile_public_info_save'
  get  '/profile/password_change'             , to: 'front_profile#user_profile_password_change_edit'
  post '/profile/password_change'             , to: 'front_profile#user_profile_password_change_save'
  get  '/profile/change_email'                , to: 'front_profile#user_profile_change_email_edit'
  post '/profile/change_email'                , to: 'front_profile#user_profile_change_email_save'
  post '/profile/subscribe_notifications'     , to: 'front_profile#subscribe_notifications'
  post '/demo_push'                           , to: 'pages#demo_push'
  # get  '/profile/my_events'                   , to: 'front_profile#user_profile_my_events_list'
  # get  '/profile/my_events/:my_event_id'      , to: 'front_profile#user_profile_my_events_show'
  # post '/profile/my_events/:my_event_id'      , to: 'front_profile#user_profile_my_events_save'
  # get  '/profile/my_events/:my_event_id/edit' , to: 'front_profile#user_profile_my_events_show'
  # PAYMENT CALLBACKS STARTED
  # post "/webhooks/stripe", to: "pay/webhooks/stripe#create"

  get  "/payment_success/:ticket_payment_id", to: 'pages#ticket_transaction_payment_success'
  get  "/payment_cancel/:ticket_payment_id" , to: 'pages#ticket_transaction_payment_cancel'


  get '/vehicle_img_sm/:vimg_id', :controller => :pages, action: :pub_vehicle_sm_img
  get '/user_station_img_sm/:simg_id', :controller => :pages, action: :pub_user_station_sm_img

  namespace :profile, format: false do
    resources :my_payout_options, module: :my_payout_options, param: :poption_id
    resources :my_notifications, module: :my_notifications, param: :my_notification_id, only: [:index, :show]
    resources :my_tickets, module: :my_tickets, param: :ticket_id, only: [:index, :new, :show, :create, :update] do
      get :pay
    end
    resources :my_vehicles, module: :my_vehicles, param: :my_vehicle_id do
      resources :vehicle_imgs, param: :eimg_id, only: %w{index create destroy} do

      end
      member do
        post :choose_vimage_as_logo
      end
    end

    resources :my_stations, module: :my_stations, param: :my_station_id do
      resources :station_imgs, param: :simg_id, only: %w{index create destroy} do

      end
      member do
        post :choose_simage_as_logo
      end
    end

    resources :my_routes, module: :my_routes, param: :my_route_id do
      resources :route_points, param: :rp_id do

      end
      # member do
      #   post :choose_simage_as_logo
      # end
    end

    resources :my_trips, module: :my_trips, param: :my_trip_id do
      resources :trip_points, param: :trp_id do

      end
      member do
        get  :publish_flag
        post :publish_flag, to: 'my_trips#publish_flag_update'
      end
      # resources :route_points, param: :rp_id do

      # end
    end

    resources :my_events, module: :my_events, param: :my_event_id do
      resources :tickets_packs, param: :tpack_id do

      end
      member do
        get :images
        get  :my_chat
        post :my_chat, to: 'my_events#my_chat_add_msg'
        get  :payout
        post :payout , to: 'my_events#payout_run'
        post   :choose_image_as_logo
        post   :create_image_attachment
        post   :change_event_status
      end
    end

    resources :sold_tickets, module: :sold_tickets, param: :sold_ticket_id
  end

end

app/models/trip.rb
# frozen_string_literal: true

class Trip < ApplicationRecord
  NO_LOGO_IMG_PATH = '/pics/no_image.png'.freeze

  belongs_to :vehicle
  belongs_to :user_route
  has_many :trip_chat_msgs, dependent: :destroy

  has_many :trip_ticket_packs, dependent: :destroy
  has_many :tickets, through: :trip_ticket_packs
  has_many :payed_tickets, -> { where("tickets.ticket_payed_at IS NOT NULL") }, through: :trip_ticket_packs, source: :tickets
  has_many :users_with_payed_ticket, -> { distinct }, through: :payed_tickets, source: :user

  scope :active        , -> { where(deleted_at: nil) }
  scope :published_only, -> { where(published: 1) }


  validates :starts_at_unix, numericality: { greater_than_or_equal_to: 1, only_integer: true }, presence: true
  validates :all_trip_tickets_cnt, numericality: { greater_than_or_equal_to: 0, only_integer: true }, presence: true
  validate :validate_same_user_route_and_vehicle

  def validate_same_user_route_and_vehicle
    if errors.empty? && vehicle && user_route
      unless user_route.user_id.eql?(vehicle.user_id)
        errors.add(:vehicle, 'User should be same')
      end
    end
  end

  def trip_start_time_unix_with_default; starts_at_unix.positive? ? starts_at_unix : (Time.now + 2.hours).to_i; end
  def trip_start_time; Time.at(starts_at_unix).to_datetime.localtime; end
  def trip_start_time_with_default; Time.at(trip_start_time_unix_with_default).to_datetime.localtime; end
  def trip_finish_time_with_default; (trip_start_time_unix_with_default + user_route.route_run_seconds).to_datetime.localtime; end
  def trip_published?; published.positive?; end
  def client_trip_name_html; "<span class='client_trip_name_span'>Trip \##{ id }</span>".html_safe; end
  def trip_already_started?; trip_start_time_with_default <= Time.now.localtime; end
  def trip_already_finished?; trip_finish_time_with_default <= Time.now.localtime; end
  def trip_now_in_progress?; trip_already_started? && (!(trip_already_finished?)); end
  def trip_still_actual?; (!trip_already_finished?); end

  def trip_have_tickets_for_sale?; all_trip_tickets_cnt.positive?; end



  def trip_users_with_ticket; []; end

  def publish_status_html
    "<div class='trip_publish_status' published='#{ published }'>
      Publish status: <span>#{ trip_published? ? 'Published' : 'Not_published' }</span>
    </div>".html_safe
  end
end

app/controllers/pub_trips/points_controller.rb
class ::PubTrips::PointsController < ::PubTrips::PubTripsBaseController
  before_action :set_current_trip_point
  skip_before_action :set_current_trip_point, only: %w{index new create}


  def set_current_trip_point
    return @current_trip_point if @current_trip_point
    add_breadcrumb "TripPoints", trip_points_path(@front_side_current_trip.id)
    id = params[:trp_id] || params[:trip_trp_id] || 0
    result = @front_side_current_trip.user_route.user_route_points.detect { |x| x.id.eql?(id.to_i) }
    unless result
      raise ActionController::RoutingError.new("TripPoint[#{ id }] not found in trip[#{ @front_side_current_trip.id }]")
    end
    add_breadcrumb "TripPoint \##{ result.id }", trip_point_path(@front_side_current_trip.id, result.id)
    main_data[:title] = "TripPoint \##{ result.id }"
    @current_trip_point = result
    result
  end

  def index
    add_breadcrumb "TripPoints", profile_my_trip_trip_points_path(@front_side_current_trip.id)
    # @item = @front_side_current_trip.trip_points.new()
    main_data[:title] = "TripPoints"
    @items = @front_side_current_trip.user_route.valid_route_points
  end

  def show
    @item = @current_trip_point
  end


end

app/controllers/pub_trips/pub_trips_base_controller.rb
# frozen_string_literal: true

class ::PubTrips::PubTripsBaseController < ::PagesController
  add_breadcrumb "Trips", :trips_path
  before_action :set_front_side_current_trip

  def set_front_side_current_trip
    return @front_side_current_trip if @front_side_current_trip
    id = params[:tr_id] || params[:trip_tr_id]
    result = Trip.find(Integer(id))
    unless result
      raise ActionController::RoutingError.new("Trip #{ id } not found")
    end
    main_data[:title] = "Trip \##{ result.id }"
    add_breadcrumb main_data[:title], trip_path(result.id)
    @front_side_current_trip = result
    result
  end

  helper_method :can_current_user_read_trip_chat?
  def can_current_user_read_trip_chat?
    return false unless current_user && @front_side_current_trip
    # result = false
    # current_user.tickets.where(event_ticket_pack: @front_side_current_trip.trip_ticket_packs).each do |ticket|
    #   result = true if ticket.ticket_allow_user_to_see_chat?
    # end
    # result
    true
  end
end

app/controllers/pub_trips/trips_controller.rb
# frozen_string_literal: true

class ::PubTrips::TripsController < ::PubTrips::PubTripsBaseController
  skip_before_action :set_front_side_current_trip, only: %w{index new create}


  def index
    per_page = 24
    # data = ::PubTripsSearchHelper.get_trips_collection(params)
    # events = data[:items]
    search_item = { name: 'Search', prop_name: :search }
    # @filter_items = [search_item] + data[:filter_items]
    ids_sql = ::PubTripsSearchHelper.get_search_where_sql(params[:search].to_s, true)
    @filter_items = [search_item]
    # @items = events.page(params_page).per(per_page)
    @items = Trip.active.published_only.where(ids_sql).page(params_page).per(per_page)
  end

  def show
    @item = @front_side_current_trip
  end

  def chat
    @new_msg = TripChatMsg.new
    @items = load_chat_msgs_list
    @unread_ids = load_unreaded_msgs_ids_and_mark_them_readed(@items)
  end

  def load_chat_msgs_list
    per_page = 30
    main_data[:title] = "Trip \##{ @front_side_current_trip.id } Chat"
    add_breadcrumb 'Chat', chat_trip_path(@front_side_current_trip.id)
    search_attrs = can_current_user_read_trip_chat? ? { trip: @front_side_current_trip } : { id: 0 }
    TripChatMsg.where(search_attrs).order(id: :DESC).page(params_page).per(per_page)
  end

  def load_unreaded_msgs_ids_and_mark_them_readed(msgs)
    result = []
    TripChatMsgUnread.where(user: current_user).where(trip_chat_msg_id: msgs.map(&:id)).includes(:trip_chat_msg).each do |umsg|
      result.push(umsg.trip_chat_msg_id)
      if (umsg.trip_chat_msg.created_at + 5.seconds) < Time.now()
        umsg.destroy!
      end
    end
    result
  end

  def chat_add_msg
    @new_msg = TripChatMsg.new
    new_html = params[:msg_text].strip.gsub(/[\r]+/, "").text_to_html
    if can_current_user_read_trip_chat? && new_html.size_positive?
      new_attrs = { user: current_user, msg_html: new_html }
      @new_msg = @front_side_current_trip.trip_chat_msgs.create!(new_attrs)
      if @new_msg.id && @new_msg.id.positive?
        return redirect_to chat_trip_path(@front_side_current_trip.id)
      end
    end
    @items = load_chat_msgs_list
    @unread_ids = load_unreaded_msgs_ids_and_mark_them_readed(@items)
    flash2 :alert, "Errors found"
    render action: :chat
  end
end

app/views/pub_trips/trips/_front_trips_list_item.html.erb
<div class="catalog_item_main_block" >
   <div class="catalog_item2">
      <a class="catalog_item_img_block2" href='<%= trip_path(item.id) %>' onclick="return show_in_modal_link(this, 'proj_modal_main trip_modal');" name='trip_<%= item.id %>' >
        <% if item.vehicle.valid_vehicle_imgs.any? %>
          <div class="owl-carousel owl-theme owl_prod_list_slider">
            <% item.vehicle.valid_vehicle_imgs.each do |sm_img| %>
              <div class='item'>
                 <table>
                    <tbody>
                       <tr>
                          <td>
                            <img class='slider_sm_img' src='<%= sm_img.image_sm_url %>' />
                          </td>
                       </tr>
                    </tbody>
                 </table>
              </div>
            <% end %>
         </div>
        <% else %>
          <div class="catalog_item_subimg_block">
            <div class="catalog_item_img_cell">
              <img src="/pics/no_image.png" alt="" title="" />
            </div>
          </div>
        <% end %>
      </a>
      <div class="catalog_item_body">
         <div class="catalog_item_top_block">
            <div class="name_rate">
               <div class="catalog_item_title">
                  <a href="<%= trip_path(item.id) %>" onclick="return show_in_modal_link(this, 'proj_modal_main trip_modal');" name='trip_<%= item.id %>'>
                    <%= item.user_route.name.to_s.ehtml %>
                  </a>
               </div>
            </div>
            <div class="catalog_item_price">

            </div>
            <div class='available'>
              <%= item.publish_status_html %>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/pub_trips/trips/chat.erb
<div class="row event_chat_main_block">
  <form class="w500_centerd base_style client_msgs_list_block" method='POST' action="<%= chat_trip_path(@front_side_current_trip.id) %>" onsubmit="return run_ajax_submit_if_modal(this);" success_func="refresh_model_items_htmls_in_list">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="row hidden_in_modal">
      <div class="col-12">
        <div class="form-group">
          <h3 class="col-12">Chat of trip
            <a href="<%= trip_path(@front_side_current_trip.id) %>">
              <%= @front_side_current_trip.client_trip_name_html %>
            </a>
          </h3><br/>
        </div>
      </div>
    </div>
    <% unless can_current_user_read_trip_chat? %>
      <div class="row">
        <div class="col-12">
          <div class="text-danger">
            <h3>You can not see this chat. Authorize and get a ticket first.</h3>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-12">
        <div class="text-right">
          <div class="wph_page_pagination">
            <%= paginate @items %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <table class="table messages_list_table">
          <tbody>
          <% TripChatMsg.pack_by_src_ca_name_trip_chat_msgs(@items, current_user.id).each_with_index do |msg_data, indx| %>
              <tr class="message_tr client_event_chat_msg_tr list_item_main_block src_ca_ind_<%= msg_data[:src_ca_ind] %>">
                <td class="message_src_ca_td">
                  <div class="col-12">
                    <div class="row">
                      <div class="col-12">
                        <a class='msg_src_ca_name_link' href="<%= user_path(msg_data[:ca_id]) %>" onclick="return show_in_modal_link(this, 'proj_modal_main user_info_modal');" name="user_<%= msg_data[:ca_id] %>">
                          <%= msg_data[:ca_name].ehtml %>
                        </a>
                      </div>
                    </div>
                    <% msg_data[:msgs_arr].each do |msg| %>
                      <div class="row message_text_row <%= @unread_ids.include?(msg.id) ? 'unread_by_ca_msg' : '' %>">
                        <div class="col-8 msg_texts_html_block">
                          <%= msg.msg_text_html.html_safe %>
                        </div>
                        <div class="col-4">
                          <%= msg.created_at.client_stamp_html %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row add_new_msg_block">
      <div class="col-12 no_padding_left">
        <div class="row">
          <div class="col-9 hidden_if_form_loading_update_with_xhr">
            <textarea class='form-control form-control-sm' rows='3' name='msg_text' placeholder='Message'><%= params[:msg_text].to_s.ehtml %></textarea>
          </div>
          <div class="col-3 no_padding hidden_if_form_loading_update_with_xhr">
            <button type="submit" class='btn btn-outline-success btn-sm'>Send</button><br/>
            <div class="hidden_in_modal">
              <button type="button" class='btn btn-outline-primary btn-sm each_5_seconds_btn' already_runned='0' onclick="return refresh_messages_in_list(this);">Refresh</button>
            </div>
          </div>
        </div>
        <br/><br/><br/><br/>
      </div>
    </div>
  </form>
</div>

app/views/pub_trips/trips/index.erb
<div class='row front_content_main_row front_trips_list_main_row'>
  <div class="col-12">
    <div class="row front_page_title_row">
      <div class="col-12">
        <h3>Search for trips</h3>
      </div>
    </div>
    <div class="row front_page_content_row">
      <%= render(:partial => 'layouts/trips_filters', locals: { filter_items: @filter_items }) %>
      <div class="col-12 front_trips_list_block">
        <div class="row front_trips_head_row">
          <div class="col-5">
            Found <%= @items.total_count %> trips
          </div>
          <div class="col-7 pagination_col">
            <%= paginate @items %>
          </div>
        </div>
        <div class="row front_trips_list_row">
          <% @items.each do |item| %>
            <div class="col-12 col-md-6 col-lg-4 col-xl-3 catalog_item_wrapper front_trips_list_item">
              <%= render(:partial => 'front_trips_list_item', locals: { item: item }) %>
            </div>
          <% end %>
        </div>
        <div class="row front_trips_bottom_row">
          <div class="col-5">&nbsp;</div>
          <div class="col-7 pagination_col">
            <%= paginate @items %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pub_trips/trips/show.erb
<div class='row front_content_main_row front_parties_edit_main_row'>
  <div class="col-12 sm_no_padding row_np3" id="content">
    <div class="container">
      <div class="event_card_main_block">
        <form class="event_card_page_wrapper" method="GET" action='/cart/add/<%= @item.id %>'>
          <div class="card_slider product_card_slider">
            <div class="card_main_slider synchronized_2_sliders" sync_slider_id='0'>
              <a href="#" class='open_card_imgs_galery_btn' title="Open image in new tab" target="_blank"></a>
              <div class="owl-carousel owl-theme sync_large_slider">
                <% @item.vehicle.valid_vehicle_imgs.each do |big_img| %>
                  <div class='item'>
                    <table>
                      <tbody>
                        <tr>
                          <td>
                            <img class='slider_sm_img' src='<%= url_for(big_img.image_file) %>' />
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                <% end %>
              </div>
              <div class="owl-carousel owl-theme sync_small_slider">
                <% @item.vehicle.valid_vehicle_imgs.each do |sm_img| %>
                  <div class='item'>
                    <table>
                      <tbody>
                        <tr>
                          <td>
                            <img class='slider_sm_img' src='<%= sm_img.image_sm_url %>' />
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="event_card_info card_info_main_block">
            <link itemprop="availability" href="http://schema.org/InStock" />
            <meta itemprop="price" content="{price_conv_html}" />
            <div class="row">
              <div class="col-12">
                <div class="event_card_title">
                  Trip <%= @item.user_route.name.to_s.ehtml %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-6">
                <div class="event_id small-text">TripID: <span><%= @item.id %></span></div>
              </div>
              <div class="col-6 text-right">
                <div class="event_stars">
                  <img src="/pics/stars.png" alt="Product raiting" />
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <div class="available small-text"><%= @item.publish_status_html %></div> by user
                <a href="<%= user_path(@item.user_route.user.id) %>" onclick="return show_in_modal_link(this, 'proj_modal_main user_modal');">
                  <%= @item.user_route.user.name_or_email_for_public.ehtml %>
                </a>
              </div>
            </div>
            <% if @item.trip_have_tickets_for_sale? %>
              <div class="row event_ticket_packs_row">
                <div class="col-12">
                  <b>Tickets exists</b>
                </div>
              </div>
            <% end %>
            <div class="row">
              <div class="col-12">
                <table class='table table-sm'>
                  <thead>
                    <tr>
                      <th colspan="3">
                        Start at: <%= @item.trip_start_time.client_stamp_html %>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @item.user_route.valid_route_points.each_with_index do |rpoint, indx| %>
                      <tr>
                        <td><%= indx + 1 %></td>
                        <td>
                          <img src="<%= rpoint.route_logo_sm_url %>" />
                        </td>
                        <td>
                          Station: <%= rpoint.user_station.name.ehtml %><br/><br/>
                          Visit: <%= rpoint.visit_time_html(@item.trip_start_time_unix_with_default) %>
                        </td>
                        <td>
                          <a href="<%= trip_point_path(@item.id, rpoint.id) %>" class="fa fa-edit" aria-hidden="true" title='View route point info' onclick="return show_in_modal_link(this, 'proj_modal_main trip_point_modal');"></a>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <% if current_user %>
              <div class="row">
                <div class="col-6 text-right">
                  <!--noindex-->
                    <br/><br/><br/>
                    <a href="<%= chat_trip_path(@item.id) %>" class='btn btn-outline-success btn-sm' onclick="return show_in_modal_link(this, 'proj_modal_main chat_trip_modal');" name="chat_trip_<%= @item.id %>">
                      Go chat!
                    </a>
                  <!--/noindex-->
                </div>
              </div>
            <% end %>
          </div>
          <br/><br/><br/>
        </form>
        <div class="card-tabs-wrapper">

        </div>
      </div>
    </div>
  </div>
</div>