config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path => '/profile', controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }

  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#main_page'
  # get '/test_path', to: 'pages#test_path'
  get '/video'    , to: 'pages#video'
  get '/about'    , to: 'pages#about'
  get '/gifs_some1'    , to: 'pages#gifs_some1'
  get '/gg5_v1'    , to: 'pages#gg5_v1'
  get '/gg5_v2'    , to: 'pages#gg5_v2'
  get '/games', to: 'pages#games'
  get '/new_animes', to: 'pages#new_animes'
  get '/create_animes_snapshot', to: 'pages#create_animes_snapshot'



  # get '/parties'                                , to: 'pages#front_parties_list'
  # get '/parties/:party_id'                      , to: 'pages#front_parties_edit'
  # get '/parties/:party_id/buy_ticket/:tpack_id' , to: 'pages#front_parties_buy_ticket'

  resources :queues, module: :pub_task_queues, param: :tq_id, only: [:index, :show, :update] do

  end
  # resources :tasks, module: :front_users_module, param: :front_user_id, only: [:index, :show] do

  #   end

  resources :users, module: :front_users_module, param: :front_user_id, only: [:index, :show] do

  end

  resources :parties, module: :parties_module, param: :party_id, only: [:index, :show] do
    resources :tickets, module: :buy_ticket_module, param: :tpack_id, only: [:index] do

    end
    member do
      get :chat
      post :chat, to: 'parties#chat_add_msg'
    end
  end

  resources :trips, module: :pub_trips, param: :tr_id, only: [:index, :show] do
    resources :points, param: :trp_id, only: [:index, :show] do

    end
    member do
      get :chat
      post :chat, to: 'trips#chat_add_msg'
    end
  end

  resources :stations, module: :pub_stations, param: :st_id, only: [:index, :show] do

  end


  get  '/profile'                             , to: 'front_profile#user_profile_show', as: :user_root
  get  '/profile/public_info'                 , to: 'front_profile#user_profile_public_info_edit'
  post '/profile/public_info'                 , to: 'front_profile#user_profile_public_info_save'
  get  '/profile/password_change'             , to: 'front_profile#user_profile_password_change_edit'
  post '/profile/password_change'             , to: 'front_profile#user_profile_password_change_save'
  get  '/profile/change_email'                , to: 'front_profile#user_profile_change_email_edit'
  post '/profile/change_email'                , to: 'front_profile#user_profile_change_email_save'
  post '/profile/subscribe_notifications'     , to: 'front_profile#subscribe_notifications'
  post '/demo_push'                           , to: 'pages#demo_push'
  # get  '/profile/my_events'                   , to: 'front_profile#user_profile_my_events_list'
  # get  '/profile/my_events/:my_event_id'      , to: 'front_profile#user_profile_my_events_show'
  # post '/profile/my_events/:my_event_id'      , to: 'front_profile#user_profile_my_events_save'
  # get  '/profile/my_events/:my_event_id/edit' , to: 'front_profile#user_profile_my_events_show'
  # PAYMENT CALLBACKS STARTED
  # post "/webhooks/stripe", to: "pay/webhooks/stripe#create"

  get  "/payment_success/:ticket_payment_id", to: 'pages#ticket_transaction_payment_success'
  get  "/payment_cancel/:ticket_payment_id" , to: 'pages#ticket_transaction_payment_cancel'


  get '/vehicle_img_sm/:vimg_id', :controller => :pages, action: :pub_vehicle_sm_img
  get '/user_station_img_sm/:simg_id', :controller => :pages, action: :pub_user_station_sm_img

  namespace :profile, format: false do
    resources :my_payout_options, module: :my_payout_options, param: :poption_id
    resources :my_notifications, module: :my_notifications, param: :my_notification_id, only: [:index, :show]
    resources :my_tickets, module: :my_tickets, param: :ticket_id, only: [:index, :new, :show, :create, :update] do
      get :pay
    end
    resources :my_vehicles, module: :my_vehicles, param: :my_vehicle_id do
      resources :vehicle_imgs, param: :eimg_id, only: %w{index create destroy} do

      end
      member do
        post :choose_vimage_as_logo
      end
    end

    resources :my_stations, module: :my_stations, param: :my_station_id do
      resources :station_imgs, param: :simg_id, only: %w{index create destroy} do

      end
      member do
        post :choose_simage_as_logo
      end
    end

    resources :my_routes, module: :my_routes, param: :my_route_id do
      resources :route_points, param: :rp_id do

      end
      # member do
      #   post :choose_simage_as_logo
      # end
    end

    resources :my_trips, module: :my_trips, param: :my_trip_id do
      resources :trip_points, param: :trp_id do

      end
      member do
        get  :publish_flag
        post :publish_flag, to: 'my_trips#publish_flag_update'
      end
      # resources :route_points, param: :rp_id do

      # end
    end

    resources :my_events, module: :my_events, param: :my_event_id do
      resources :tickets_packs, param: :tpack_id do

      end
      member do
        get :images
        get  :my_chat
        post :my_chat, to: 'my_events#my_chat_add_msg'
        get  :payout
        post :payout , to: 'my_events#payout_run'
        post   :choose_image_as_logo
        post   :create_image_attachment
        post   :change_event_status
      end
    end

    resources :sold_tickets, module: :sold_tickets, param: :sold_ticket_id
  end

end

app/views/pages/about.erb
<h2 class="mt-5">About page</h2>
<br/>
Project repository: <a href="https://github.com/trumenov/shuttle_bus" target="_blank">https://github.com/trumenov/shuttle_bus</a><br/>
<br/><br/>

AndrewTrumenov CVs and other files for HRs:<br/>
<div class='col-12'>
  <div class="row">
    <div class='col-12'>
      <table class='table table-sm'>
        <thead>
          <tr>
            <th>File</th>
            <th>FileSize</th>
            <th>AddedAt</th>
          </tr>
        </thead>
        <tbody>
          <% Dir.entries("#{Rails.root}/public/about").sort_by { |x| File.ctime("#{Rails.root}/public/about/#{x}") }.each do |file_name| %>
            <% next if file_name == '.' || file_name == '..' %>
            <% file_path = "#{Rails.root}/public/about/#{file_name}" %>
            <tr>
              <td>
                <a href="/about/<%= file_name.eurl %>" target='_blank'>
                  <%= file_name.ehtml %>
                </a>
              </td>
              <td><%= number_to_human_size(File.size(file_path)) %></td>
              <td><%= File.ctime(file_path) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br/><br/>

Chernuha Andrey CV at GoogleDocs:<br/>
<a href="https://docs.google.com/document/d/1QOV2pPKAEm1vfOBv7O-ax2NGmZgqDz5u" target="_blank" title='Thanks for this cool template for HR @vr_leba. Вероника, спасибо Вам огромное, надеюсь людям понравится такой формат). Всегда буду рад помочь Вам по возможности чем смогу так сказать.'>
  2022 resume AndrewChernuha_2022_3.docx
</a><br/>
<a href="https://drive.google.com/file/d/1t-B-9rwLtn6ys1L0hoemfV9zP_PEmXHl" target="_blank">
  Current last resume AndrewChernuha_2023_1.docx
</a><br/>
<br/><br/>
Old CV files for last few years:<br />
<a href="https://docs.google.com/document/d/1AkvtFuJ4BmgS_Mz-NUPsnHjSLDB_9XQ2" target="_blank">
  Chernukha Andrey Pavlovich_2020.docx
</a><br/>
<a href="https://docs.google.com/document/d/14fydu-w1nZcxO-6XQ97KEUb82mUDWDD0EV-4t05T3QA" target="_blank">
  Chernukha Andrey.doc (2021)
</a><br/>
<a href="https://docs.google.com/document/d/1nsdspvxL3eReuuTym432fxIGiWPJl3PPoIFiLNntDgU" target="_blank">
  Chernukha Andrey2022.doc
</a><br/><br/>
<h2>Linkedin profile:</h2>
<a href="https://www.linkedin.com/in/andrey-ror-perl/" target="_blank">https://www.linkedin.com/in/andrey-ror-perl/</a><br/>
<br/><br/>
This is <a href='mailto::chaky22222222@gmail.com'>chaky22222222@gmail.com</a> demo project. <br/>
Some code from <a target="_blank" href="https://test.vint.com.ua/">https://test.vint.com.ua</a> - this is new front still in dev mode for <a href="https://vint.com.ua" target="_blank">https://vint.com.ua</a>.
<br/><br/><br/>
<br/><br/>

app/views/pages/front_parties_buy_ticket.erb
front_parties_buy_ticket here

app/views/pages/games.erb
<h2 class="mt-5">Games</h2>
<br/>
<div class='col-12'>
  <div class="row">
    <div class='col-12'>
      <table class='table'>
        <thead>
          <tr>
            <th>File</th>
            <th>FileSize</th>
            <th>AddedAt</th>
          </tr>
        </thead>
        <tbody>
          <% Dir.foreach("#{Rails.root}/public/games") do |file_name| %>
            <% next if file_name == '.' || file_name == '..' %>
            <% file_path = "#{Rails.root}/public/games/#{file_name}" %>
            <tr>
              <td>
                <a href="/games/<%= file_name.eurl %>" target='_blank'>
                  <%= file_name.ehtml %>
                </a>
              </td>
              <td><%= number_to_human_size(File.size(file_path)) %></td>
              <td><%= File.ctime(file_path) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br/><br/>

app/views/pages/gg5_v1.erb
<h2 class="mt-5">gg5_v1</h2>
<br/>
<div class='col-12'>
  <div class="row">
    <div class='col-12'>
      <table class='table'>
        <thead>
          <tr>
            <th>File</th>
            <th>FileSize</th>
            <th>AddedAt</th>
          </tr>
        </thead>
        <tbody>
          <% Dir.foreach("#{Rails.root}/public/shara/gg5_v1").sort.each do |file_name| %>
            <% next if file_name == '.' || file_name == '..' %>
            <% file_path = "#{Rails.root}/public/shara/gg5_v1/#{file_name}" %>
            <tr>
              <td>
                <a href="/video?f=<%= "gg5_v1/#{file_name}".eurl %>" >
                  <%= file_name.ehtml %>
                </a>
              </td>
              <td>
                <a href="/shara/gg5_v1/<%= file_name.eurl %>" target='_blank'>
                  <%= number_to_human_size(File.size(file_path)) %>
                </a>
              </td>
              <td><%= File.ctime(file_path) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br/><br/>

app/views/pages/gg5_v2.erb
<h2 class="mt-5">gg5_v2</h2>
<br/>
<div class='col-12'>
  <div class="row">
    <div class='col-12'>
      <table class='table'>
        <thead>
          <tr>
            <th>File</th>
            <th>FileSize</th>
            <th>AddedAt</th>
          </tr>
        </thead>
        <tbody>
          <% Dir.foreach("#{Rails.root}/public/shara/gg5_v2").sort.each do |file_name| %>
            <% next if file_name == '.' || file_name == '..' %>
            <% file_path = "#{Rails.root}/public/shara/gg5_v2/#{file_name}" %>
            <tr>
              <td>
                <a href="/video?f=<%= "gg5_v2/#{file_name}".eurl %>" >
                  <%= file_name.ehtml %>
                </a>
              </td>
              <td>
                <a href="/shara/gg5_v2/<%= file_name.eurl %>" target='_blank'>
                  <%= number_to_human_size(File.size(file_path)) %>
                </a>
              </td>
              <td><%= File.ctime(file_path) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br/><br/>

app/views/pages/gifs_some1.erb
<h2 class="mt-5">gifs_some1</h2>
<br/>
<div class='col-12'>
  <div class="row">
    <% Dir.foreach("#{Rails.root}/public/gifs_some1") do |image| %>
      <% next if image == '.' || image == '..' %>
      <div class="col-4 mt-5">
        <img style='display: inline-block; max-width: 100%;' src="/gifs_some1/<%= image.to_s.eurl %>" />
      </div>
    <% end %>
  </div>
</div>
<br/><br/>

app/views/pages/main_page.html.erb
<div class="row">
  <div class="col-12">
    <h5>This is a demo project with bootstrap4 and ajax mixed modals</h5>
    <small>
      <ul>
        <li>Rails6 (Ruby 2.7.2) with breadcrumbs</li>
        <li>MySql</li>
        <li>Devise (omniauth-google-oauth2, omniauth-facebook)</li>
        <li>Capistrano3 as deployment system</li>
        <li>Front side: Bootstrap4 + JQuery + OwlCarousel + Select2</li>
      </ul>
    </small>
    <a href="/trips" class='btn btn-outline-primary btn-sm'>Choose trip</a>
    <br/><br/><br/>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <b>My demo shop (der2shop) with excel import/export examples and funny filters:</b><br/>
    <a href="https://d.hw.dp.ua" target="_blank">d.hw.dp.ua</a>
    <br/><br/>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <b>My shop with russian localization for my neighbors:</b><br/>
    <a href="https://herb.hw.dp.ua" target="_blank">herb.hw.dp.ua</a>
    <br/><br/>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <b>My demo project with excel import/export examples here:</b><br/>
    <a href="https://sapr.hw.dp.ua" target="_blank">sapr.hw.dp.ua</a>
    <br/><br/>
  </div>
</div>
<br/><br/>
This is <a href='mailto::chaky22222222@gmail.com'>chaky22222222@gmail.com</a> demo project. <br/>
Some code from <a target="_blank" href="https://test.vint.com.ua/">https://test.vint.com.ua</a> - this is new front still in dev mode for <a href="https://vint.com.ua" target="_blank">https://vint.com.ua</a>.
<br/><br/><br/>
<a href="https://github.com/trumenov/shuttle_bus" target="_blank">https://github.com/trumenov/shuttle_bus</a><br/>
<a href="https://www.linkedin.com/in/andrey-ror-perl/" target="_blank">https://www.linkedin.com/in/andrey-ror-perl/</a><br/>
<a href="/about">About this project (and CV)</a><br/>
<br/><br/><br/>
<a href="/admin/login" target="_blank">Admin dashboard</a>:<br/>
login: admin@example.com<br/>
password: password<br/>
<br/><br/>


DemoUser: <br/>
Login: megatester@test.test<br/>
password: 123123<br/>
<br/><br/><br/><br/>

app/views/pages/new_animes.erb
<h2 class="mt-5">New animes</h2>
<br/>
<div class='col-12'>
  <div class="row">
    <div class='col-12'>
      <button class="btn btn-success btn-sm" type="button" onclick="return run_create_animes_snapshot();">Create new snapshot</button>
    </div>
  </div>
  <div class="row">
    <div class='col-12'>
      <table class='table'>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% AnimeScraper.detect_new_animes.each do |anime| %>
            <tr>
              <td>
                <%= anime.first.ehtml %>
              </td>
              <td><%= anime.second.ehtml %></td>
              <td>
                <a rel="nofollow" target="_blank" href="<%= URI.parse("https://www.wcostream.tv#{anime[2]}").to_s.html_safe %>">
                  https://www.wcostream.tv<%= anime[2].to_s.ehtml %>
                </a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br/><br/>

<script type="text/javascript">
  function run_create_animes_snapshot() {
    const p_val = prompt('p');

    console.log('p_val=', p_val);

    if (!p_val) return false;
    document.location.href='/create_animes_snapshot?p=' + p_val;
    return false;
  }

</script>

app/views/pages/ticket_transaction_payment_cancel.erb
<div class='row front_content_main_row profile_event_tpacks_main_row'>
  <div class="w350_centerd" id="content">
    <div class="row front_page_content_row">
      <div class="col-12">
        <div class="row hidden_in_modal">
          <div class="col-12"><br/><br/>
            <h3 class='text-danger'>Payment fail.</h3><br/>
            <h4>Your payment not received.</h4>
          </div>
        </div>
        <div class="row front_edit_form">
          <div class="col-12">
            Your payment not received.<br/><br/>
            You can found your ticket in your account profile on <a href="<%= profile_my_tickets_path %>">My tickets</a> page and try to pay it again.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/ticket_transaction_payment_success.erb
<div class='row front_content_main_row profile_event_tpacks_main_row'>
  <div class="w350_centerd" id="content">
    <div class="row front_page_content_row">
      <div class="col-12">
        <div class="row hidden_in_modal">
          <div class="col-12"><br/><br/>
            <h3 class='text-success'>Success!</h3><br/>
            <h4>Your payment received!</h4>
          </div>
        </div>
        <div class="row front_edit_form">
          <div class="col-12">
            Your payment received.<br/><br/>
            You can found your ticket in your account profile on <a href="<%= profile_my_tickets_path %>">My tickets</a> page.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/video.erb
<h2 class="mt-5">Play video</h2>
<br/>
<div class='col-12'>
  <div class="row">
    <div class='col-12'>
      <% if @item_relative_path.present? %>
        <video width="100%" height="auto" controls="true" preload="none" src="<%= @item_relative_path %>" type="video/mp4" >

        </video>
      <% else %>
        Not found file [<%= params[:f].to_s.ehtml.html_safe %>]
      <% end %>
    </div>
  </div>
</div>
<br/><br/>